apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: devops-training
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: api
  type: LoadBalancer
  
  #ให้ access มาจากที่อื่นได้ ในที่นี้คือ LoadBalancer 
  #access from internet to cluster